/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c4c7c9",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-fixed-variant": "#444749",
        "on-background": "#0b1c30",
        "error": "#ba1a1a",
        "outline-variant": "#c6c6cd",
        "on-primary": "#ffffff",
        "background": "#f8f9ff",
        "on-secondary": "#ffffff",
        "primary-container": "#131b2e",
        "on-error-container": "#93000a",
        "on-surface-variant": "#45464d",
        "on-surface": "#0b1c30",
        "surface": "#f8f9ff",
        "error-container": "#ffdad6",
        "surface-dim": "#cbdbf5",
        "on-secondary-container": "#626567",
        "surface-tint": "#565e74",
        "tertiary-container": "#171c1f",
        "on-tertiary-container": "#808488",
        "outline": "#76777d",
        "on-tertiary-fixed": "#171c1f",
        "on-tertiary-fixed-variant": "#43474b",
        "secondary": "#5c5f61",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "primary-fixed": "#dae2fd",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed-variant": "#3f465c",
        "primary": "#000000",
        "inverse-primary": "#bec6e0",
        "on-secondary-fixed": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        "tertiary-fixed": "#dfe3e7",
        "on-tertiary": "#ffffff",
        "tertiary": "#000000",
        "tertiary-fixed-dim": "#c3c7cb",
        "on-primary-container": "#7c839b",
        "inverse-surface": "#213145",
        "secondary-fixed": "#e0e3e5",
        "secondary-container": "#e0e3e5",
        "surface-variant": "#d3e4fe"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        xxl: "1.5rem",
        full: "9999px"
      },
      spacing: {
        "container-max": "1280px",
        xs: "4px",
        sm: "8px",
        xl: "40px",
        md: "16px",
        lg: "24px",
        unit: "4px",
        xxl: "64px",
        gutter: "24px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display": ["'Playfair Display'", "serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }],
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
